### ISSUE TITLE
V2 Beta as release

### ISSUE THREAD

**Issue by pranavburnwal** [irusanov/ZenStates#16]
Hi,

Thanks for the amazing tool! 
Just wanted to check when you plan to release v2.0.0 (i found the debug version on forums) as a release?

PS: Noob question, For me Max Boost Single core doesn't kick in for some reason. and my processor Always hovers its values around my mAx Boost all clock setting regardless of what. Never goes towards idle frequent even when not used. 
I am pretty sure I might be doing something wrong. Please advise if can. 

My current configuration is:
![image](https://user-images.githubusercontent.com/15976005/94386761-fc920d00-017a-11eb-8921-8e2ef1b04b92.png)
I also use Park control to park 50% of my cores when not used. 

Thank you for your time and help!

**Comment by irusanov** [comment]
I'm busy with ZenTimings. Unfortunately can't provide ETA for ZenStates v2.0.

**Comment by pranavburnwal** [comment]
Oh Okay. 
Any other suggestions for a noob like me?

Thanks for your help. I will close this later.

**Comment by irusanov** [comment]
I can try to update the old app until the new one is ready.
