### ISSUE TITLE
Getting CPUH Error: WinRing DLL_INITIALIZE_ERROR

### ISSUE THREAD

**Issue by andre-ss6** [irusanov/ZenStates#17]
I've been getting this error all of a sudden now. What could this be? I re-extracted the app (latest release) to make sure the files are correct, but still getting this error when trying to start the ZenStatesSrv service.

**Comment by irusanov** [comment]
Broken UAC maybe?

**Comment by andre-ss6** [comment]
Hmmm 🤔 What do you mean? How would I debug that?

**Comment by irusanov** [comment]
Is it running with administrator privileges and have you updated windows recently?
ZenStatesSrv is not supposed to be launched by the user.
You can try to uninstall the service with the included uninstall.bat (run as administrator) or do the steps in the bat file manually.
Then start ZenStates again, which will reinstall the service.

The error you're getting is from the WinRing library not initialized, but I can't tell the reason.

**Comment by andre-ss6** [comment]
Yep, I'm running with admin privileges on.

I reinstalled the service as suggested, opened ZenStates again and now I'm getting another error on Event Log:

The WinRing0_1_2_0 service failed to start due to the following error: 
The system cannot find the path specified.

**Comment by irusanov** [comment]
Can you download [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns), then run Autoruns64.exe as administrator and delete the entry of WinRing0_1_0_2. Should be in HKLM\System\CurrentControlSet\Services section.
Then reboot and try again.

**Comment by rasmysamy** [comment]
I have had the same issue. I managed to fix it by uninstalling and moving the folder to the root of the C: drive. The issue was due to a space in the path to the installation folder that was not properly accounted for during the installation of the services, leading to the WinRing service being absent in Autoruns64 and the ZenStatesSrv service being incorrect.

**Comment by andre-ss6** [comment]
> Can you download [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns), then run Autoruns64.exe as administrator and delete the entry of WinRing0_1_0_2. Should be in HKLM\System\CurrentControlSet\Services section (or Services tab).
> Then reboot and try again.

Oh I didn't even know about this! That was it! For some reason, the entry for WinRing0_1_0_2 was pointing at EVGA Precision's folder, which I have uninstalled. 

Thanks!
